# 直接cd到这个目录，然后docker-compose up -d

version: "3.4"

services:
#   mysql:
#     image: mysql:5.5
#     build: ./mysql
#     container_name: mysql
#     ports:
#       - 3306:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: "root"
   redis:
     image: redis
     build: ./redis
     container_name: redis
     ports:
       - 6379:6379