# 直接cd到这个目录，然后docker-compose up -d

version: "3.4"

services:
  db:
    image: mysql:5.5
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - '3306:3306'
  redis:
    image: redis
    container_name: my_redis
    command: redis-server --requirepass redis@ime
    ports:
    - '6379:6379'
    volumes:
    - ./redis/data:/data
