[template]
src = "nginx.tmpl"
dest = "/etc/nginx/conf.d/bingo.conf"
#owner = "bingo"
#mode = "0644"
keys = [
  "/server"
]
check_cmd = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/service nginx reload"